[2024-05-06T21:58:38.713-0500] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-06T21:58:38.755-0500] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_excel_report.export_to_excel manual__2024-05-07T02:57:26.744042+00:00 [queued]>
[2024-05-06T21:58:38.769-0500] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_excel_report.export_to_excel manual__2024-05-07T02:57:26.744042+00:00 [queued]>
[2024-05-06T21:58:38.770-0500] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-05-06T21:58:38.793-0500] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): export_to_excel> on 2024-05-07 02:57:26.744042+00:00
[2024-05-06T21:58:38.799-0500] {standard_task_runner.py:63} INFO - Started process 65655 to run task
[2024-05-06T21:58:38.812-0500] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'mysql_to_excel_report', 'export_to_excel', 'manual__2024-05-07T02:57:26.744042+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/first.py', '--cfg-path', '/var/folders/rk/p8h75rkd3ql6mqn01ypzqgnw0000gn/T/tmpd74o0h3_']
[2024-05-06T21:58:38.815-0500] {standard_task_runner.py:91} INFO - Job 12: Subtask export_to_excel
[2024-05-06T21:58:38.918-0500] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_excel_report.export_to_excel manual__2024-05-07T02:57:26.744042+00:00 [running]> on host colpc-c02ylanslvcf.local
[2024-05-06T21:58:39.283-0500] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='mysql_to_excel_report' AIRFLOW_CTX_TASK_ID='export_to_excel' AIRFLOW_CTX_EXECUTION_DATE='2024-05-07T02:57:26.744042+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-07T02:57:26.744042+00:00'
[2024-05-06T21:58:39.285-0500] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-06T21:58:39.295-0500] {base.py:84} INFO - Using connection ID 'mysql_ecommerce' for task execution.
[2024-05-06T21:58:39.329-0500] {logging_mixin.py:188} WARNING - /Users/paulamedina/airflow/dags/first.py:15 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-05-06T21:58:39.374-0500] {logging_mixin.py:188} INFO - An error occurred while exporting data to Excel: No module named 'openpyxl'
[2024-05-06T21:58:39.375-0500] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-06T21:58:39.384-0500] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/paulamedina/airflow/dags/first.py", line 19, in export_to_excel
    df.to_excel(excel_file, index=False)
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 2417, in to_excel
    formatter.write(
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/pandas/io/formats/excel.py", line 943, in write
    writer = ExcelWriter(
             ^^^^^^^^^^^^
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/pandas/io/excel/_openpyxl.py", line 57, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paulamedina/airflow/dags/first.py", line 25, in export_to_excel
    raise AirflowException(error_message)
airflow.exceptions.AirflowException: An error occurred while exporting data to Excel: No module named 'openpyxl'
[2024-05-06T21:58:39.413-0500] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=mysql_to_excel_report, task_id=export_to_excel, execution_date=20240507T025726, start_date=20240507T025838, end_date=20240507T025839
[2024-05-06T21:58:39.432-0500] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task export_to_excel (An error occurred while exporting data to Excel: No module named 'openpyxl'; 65655)
[2024-05-06T21:58:39.468-0500] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-06T21:58:39.495-0500] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-06T21:58:39.496-0500] {local_task_job_runner.py:222} INFO - ::endgroup::
