[2024-05-06T19:23:03.757-0500] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-06T19:23:03.779-0500] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mysql_to_excel_report.export_to_excel manual__2024-05-07T00:22:56.404861+00:00 [queued]>
[2024-05-06T19:23:03.786-0500] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mysql_to_excel_report.export_to_excel manual__2024-05-07T00:22:56.404861+00:00 [queued]>
[2024-05-06T19:23:03.786-0500] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-06T19:23:03.809-0500] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): export_to_excel> on 2024-05-07 00:22:56.404861+00:00
[2024-05-06T19:23:03.837-0500] {logging_mixin.py:188} WARNING - /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=31125) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-06T19:23:03.842-0500] {standard_task_runner.py:63} INFO - Started process 31138 to run task
[2024-05-06T19:23:03.838-0500] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'mysql_to_excel_report', 'export_to_excel', 'manual__2024-05-07T00:22:56.404861+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/first.py', '--cfg-path', '/var/folders/rk/p8h75rkd3ql6mqn01ypzqgnw0000gn/T/tmpi_e5wrl6']
[2024-05-06T19:23:03.843-0500] {standard_task_runner.py:91} INFO - Job 8: Subtask export_to_excel
[2024-05-06T19:23:03.929-0500] {task_command.py:426} INFO - Running <TaskInstance: mysql_to_excel_report.export_to_excel manual__2024-05-07T00:22:56.404861+00:00 [running]> on host colpc-c02ylanslvcf.local
[2024-05-06T19:23:04.014-0500] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='mysql_to_excel_report' AIRFLOW_CTX_TASK_ID='export_to_excel' AIRFLOW_CTX_EXECUTION_DATE='2024-05-07T00:22:56.404861+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-07T00:22:56.404861+00:00'
[2024-05-06T19:23:04.017-0500] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-06T19:23:04.019-0500] {logging_mixin.py:188} INFO - An error occurred while exporting data to Excel: Using URI string without sqlalchemy installed.
[2024-05-06T19:23:04.019-0500] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-06T19:23:04.025-0500] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/paulamedina/airflow/dags/first.py", line 13, in export_to_excel
    df = pd.read_sql(query, conn_id)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/pandas/io/sql.py", line 704, in read_sql
    with pandasSQL_builder(con) as pandas_sql:
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/pandas/io/sql.py", line 903, in pandasSQL_builder
    raise ImportError("Using URI string without sqlalchemy installed.")
ImportError: Using URI string without sqlalchemy installed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paulamedina/airflow/dags/first.py", line 22, in export_to_excel
    raise AirflowException(error_message)
airflow.exceptions.AirflowException: An error occurred while exporting data to Excel: Using URI string without sqlalchemy installed.
[2024-05-06T19:23:04.039-0500] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=mysql_to_excel_report, task_id=export_to_excel, execution_date=20240507T002256, start_date=20240507T002303, end_date=20240507T002304
[2024-05-06T19:23:04.050-0500] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task export_to_excel (An error occurred while exporting data to Excel: Using URI string without sqlalchemy installed.; 31138)
[2024-05-06T19:23:04.073-0500] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-06T19:23:04.091-0500] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-06T19:23:04.092-0500] {local_task_job_runner.py:222} INFO - ::endgroup::
